spring.application.name=searchnl

spring.ai.ollama.chat.model=ferguson
spring.ai.ollama.embedding.model=qwen3-embedding

spring.ai.vectorstore.qdrant.collection-name=products
spring.ai.vectorstore.qdrant.initialize-schema=true